name: Build & Deploy Docs (via gh-pages)

on:
  push:
    branches:
      - '**' 
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install -r requirements.txt
          brew install pandoc

      - name: Manually add src/ to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Clean previous Sphinx build
        run: rm -rf docs/_build/html

      - name: Build Sphinx docs
        working-directory: docs
        run: sphinx-build -b html . _build/html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html/

